# Generated by Django 5.2.14 on 2026-05-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_value',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
