# Generated by Django 5.2.14 on 2026-05-26 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=20)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.rawrecord')),
            ],
        ),
    ]
